In [3]:
import pandas as pd

In [2]:
pd.__version__

'1.5.3'

In [4]:
cars=pd.Series(["BMW","Toyota","Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: object

In [5]:
index_cars=pd.Series(["BMW","Toyota","Honda"], index=["first","second","third"])
index_cars

first        BMW
second    Toyota
third      Honda
dtype: object

In [6]:
index_cars["first"]

'BMW'

In [7]:
color_cars=pd.Series(["Red","Blue","Green"])
color_cars

0      Red
1     Blue
2    Green
dtype: object

In [8]:
car_data=pd.DataFrame({"car_make":cars,"color":color_cars})
car_data

  car_make  color
0      BMW    Red
1   Toyota   Blue
2    Honda  Green

In [9]:
df1=pd.read_csv("student_dataset.csv")
df1

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,NaN
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,NaN
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech
6,7,Mark Blue,XYZ University,Electrical Engg,8.5,Yes,PowerGrid
7,8,Jenny Clark,ABC Institute,Computer Science,7.6,No,-
8,9,Kevin Gray,PQR College,IT,9.0,Yes,SoftNet
9,10,Laura White,XYZ University,Civil Engg,6.3,No,-
10,11,Rachel Adams,XYZ University,Computer Science,8.1,Yes,TechCorp
11,12,Peter Jones,ABC Institute,Mechanical Engg,6.9,No,-
12,13,Adam Carter,PQR College,IT,9.4,Yes,SoftNet
13,14,Megan Hall,XYZ University,Electrical Engg,7.8,Yes,ElectroTech
14,15,Olivia Black,ABC Institute,Civil Engg,6.5,No,-
15,16,David Green,PQR College,Computer Science,8.9,Yes,CodeWorks
16,17,Jessica Ray,XYZ University,Mechanical Engg,NaN,No,NaN
17,18,Harry James,PQR College,IT,8.7,Yes,SoftNet
18,19,Sophia King,ABC Institute,Electrical Engg,9.1,Yes,PowerGrid
19,20,Liam Brown,XYZ University,Civil Engg,6.8,No,-
20,21,Ethan Clark,PQR College,Computer Science,7.9,Yes,CodeWorks
21,22,Mia Roberts,XYZ University,Mechanical Engg,6.8,No,-
22,23,Noah Davis,ABC Institute,Electrical Engg,9.2,Yes,ElectroTech
23,24,Ava Miller,PQR College,Civil Engg,6.4,No,-
24,25,Lucas Allen,XYZ University,IT,8.7,Yes,SoftNet
25,26,Emma Walker,ABC Institute,Mechanical Engg,7.5,Yes,MechTech
26,27,Mason Perez,XYZ University,Electrical Engg,8.3,Yes,PowerGrid
27,28,Isabella Lee,PQR College,Computer Science,9.0,Yes,TechCorp
28,29,Jacob Brown,ABC Institute,IT,7.2,No,-
29,30,Charlotte Kim,XYZ University,Civil Engg,6.6,No,-
30,31,Olivia Green,PQR College,Computer Science,8.6,Yes,CodeWorks
31,32,Elijah Adams,ABC Institute,Mechanical Engg,7.7,Yes,MechTech
32,33,Amelia King,XYZ University,Electrical Engg,9.3,Yes,ElectroTech
33,34,Logan White,PQR College,Civil Engg,6.5,No,-
34,35,Harper Smith,ABC Institute,IT,8.1,Yes,SoftNet
35,36,James Taylor,XYZ University,Electrical Engg,7.8,Yes,PowerGrid
36,37,Ella Brown,PQR College,Computer Science,8.9,Yes,TechCorp
37,38,Henry Harris,ABC Institute,Mechanical Engg,6.9,No,NaN
38,39,Chloe Wilson,XYZ University,IT,9.1,Yes,SoftNet
39,40,Benjamin Ray,PQR College,Civil Engg,6.7,No,NaN
40,41,Liam Harris,XYZ University,Computer Science,8.5,Yes,TechCorp
41,42,Sophia Davis,ABC Institute,Civil Engg,6.8,No,-
42,43,Logan White,PQR College,Electrical Engg,9.3,Yes,ElectroTech
43,44,Ava Johnson,XYZ University,IT,7.1,No,-
44,45,Ethan Carter,ABC Institute,Mechanical Engg,8.4,Yes,MechTech
45,46,Mia Wilson,PQR College,Electrical Engg,9.0,Yes,PowerGrid
46,47,Harper Moore,XYZ University,Computer Science,7.5,Yes,CodeWorks
47,48,Mason Clark,ABC Institute,Civil Engg,6.6,No,-
48,49,Ella Brown,PQR College,IT,8.2,Yes,SoftNet
49,50,Henry Taylor,XYZ University,Electrical Engg,7.9,Yes,ElectroTech
50,51,Emily Johnson,ABC Institute,Mechanical Engg,8.7,Yes,MechTech
51,52,Amelia Green,PQR College,IT,7.3,No,-
52,53,Chloe Harris,XYZ University,Computer Science,8.8,Yes,TechCorp
53,54,Lucas White,ABC Institute,Electrical Engg,9.4,Yes,PowerGrid
54,55,Olivia Brown,PQR College,Mechanical Engg,7.7,Yes,MechTech
55,56,Noah Lee,XYZ University,Civil Engg,6.5,No,NaN
56,57,Charlotte Kim,ABC Institute,IT,8.6,Yes,SoftNet
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech
58,59,Emma Walker,XYZ University,Computer Science,7.8,Yes,CodeWorks
59,60,Benjamin Gray,ABC Institute,Mechanical Engg,6.9,No,-

In [11]:
df2=pd.read_excel("students_dataset.xlsx")
df2

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,-
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,-
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech
6,7,Mark Blue,XYZ University,Electrical Engg,8.5,Yes,PowerGrid
7,8,Jenny Clark,ABC Institute,Computer Science,7.6,No,-
8,9,Kevin Gray,PQR College,IT,9.0,Yes,SoftNet
9,10,Laura White,XYZ University,Civil Engg,6.3,No,-
10,11,Rachel Adams,XYZ University,Computer Science,8.1,Yes,TechCorp
11,12,Peter Jones,ABC Institute,Mechanical Engg,6.9,No,-
12,13,Adam Carter,PQR College,IT,9.4,Yes,SoftNet
13,14,Megan Hall,XYZ University,Electrical Engg,7.8,Yes,ElectroTech
14,15,Olivia Black,ABC Institute,Civil Engg,6.5,No,-
15,16,David Green,PQR College,Computer Science,8.9,Yes,CodeWorks
16,17,Jessica Ray,XYZ University,Mechanical Engg,7.4,No,-
17,18,Harry James,PQR College,IT,8.7,Yes,SoftNet
18,19,Sophia King,ABC Institute,Electrical Engg,9.1,Yes,PowerGrid
19,20,Liam Brown,XYZ University,Civil Engg,6.8,No,-
20,21,Ethan Clark,PQR College,Computer Science,7.9,Yes,CodeWorks
21,22,Mia Roberts,XYZ University,Mechanical Engg,6.8,No,-
22,23,Noah Davis,ABC Institute,Electrical Engg,9.2,Yes,ElectroTech
23,24,Ava Miller,PQR College,Civil Engg,6.4,No,-
24,25,Lucas Allen,XYZ University,IT,8.7,Yes,SoftNet
25,26,Emma Walker,ABC Institute,Mechanical Engg,7.5,Yes,MechTech
26,27,Mason Perez,XYZ University,Electrical Engg,8.3,Yes,PowerGrid
27,28,Isabella Lee,PQR College,Computer Science,9.0,Yes,TechCorp
28,29,Jacob Brown,ABC Institute,IT,7.2,No,-
29,30,Charlotte Kim,XYZ University,Civil Engg,6.6,No,-
30,31,Olivia Green,PQR College,Computer Science,8.6,Yes,CodeWorks
31,32,Elijah Adams,ABC Institute,Mechanical Engg,7.7,Yes,MechTech
32,33,Amelia King,XYZ University,Electrical Engg,9.3,Yes,ElectroTech
33,34,Logan White,PQR College,Civil Engg,6.5,No,-
34,35,Harper Smith,ABC Institute,IT,8.1,Yes,SoftNet
35,36,James Taylor,XYZ University,Electrical Engg,7.8,Yes,PowerGrid
36,37,Ella Brown,PQR College,Computer Science,8.9,Yes,TechCorp
37,38,Henry Harris,ABC Institute,Mechanical Engg,6.9,No,-
38,39,Chloe Wilson,XYZ University,IT,9.1,Yes,SoftNet
39,40,Benjamin Ray,PQR College,Civil Engg,6.7,No,-
40,41,Liam Harris,XYZ University,Computer Science,8.5,Yes,TechCorp
41,42,Sophia Davis,ABC Institute,Civil Engg,6.8,No,-
42,43,Logan White,PQR College,Electrical Engg,9.3,Yes,ElectroTech
43,44,Ava Johnson,XYZ University,IT,7.1,No,-
44,45,Ethan Carter,ABC Institute,Mechanical Engg,8.4,Yes,MechTech
45,46,Mia Wilson,PQR College,Electrical Engg,9.0,Yes,PowerGrid
46,47,Harper Moore,XYZ University,Computer Science,7.5,Yes,CodeWorks
47,48,Mason Clark,ABC Institute,Civil Engg,6.6,No,-
48,49,Ella Brown,PQR College,IT,8.2,Yes,SoftNet
49,50,Henry Taylor,XYZ University,Electrical Engg,7.9,Yes,ElectroTech
50,51,Emily Johnson,ABC Institute,Mechanical Engg,8.7,Yes,MechTech
51,52,Amelia Green,PQR College,IT,7.3,No,-
52,53,Chloe Harris,XYZ University,Computer Science,8.8,Yes,TechCorp
53,54,Lucas White,ABC Institute,Electrical Engg,9.4,Yes,PowerGrid
54,55,Olivia Brown,PQR College,Mechanical Engg,7.7,Yes,MechTech
55,56,Noah Lee,XYZ University,Civil Engg,6.5,No,-
56,57,Charlotte Kim,ABC Institute,IT,8.6,Yes,SoftNet
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech
58,59,Emma Walker,XYZ University,Computer Science,7.8,Yes,CodeWorks
59,60,Benjamin Gray,ABC Institute,Mechanical Engg,6.9,No,-

In [12]:
df3=pd.read_json("student_d.json")
df3

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,-
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,-
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech
6,7,Mark Blue,XYZ University,Electrical Engg,8.5,Yes,PowerGrid
7,8,Jenny Clark,ABC Institute,Computer Science,7.6,No,-
8,9,Kevin Gray,PQR College,IT,9.0,Yes,SoftNet
9,10,Laura White,XYZ University,Civil Engg,6.3,No,-
10,11,Rachel Adams,XYZ University,Computer Science,8.1,Yes,TechCorp
11,12,Peter Jones,ABC Institute,Mechanical Engg,6.9,No,-
12,13,Adam Carter,PQR College,IT,9.4,Yes,SoftNet
13,14,Megan Hall,XYZ University,Electrical Engg,7.8,Yes,ElectroTech
14,15,Olivia Black,ABC Institute,Civil Engg,6.5,No,-
15,16,David Green,PQR College,Computer Science,8.9,Yes,CodeWorks
16,17,Jessica Ray,XYZ University,Mechanical Engg,7.4,No,-
17,18,Harry James,PQR College,IT,8.7,Yes,SoftNet
18,19,Sophia King,ABC Institute,Electrical Engg,9.1,Yes,PowerGrid
19,20,Liam Brown,XYZ University,Civil Engg,6.8,No,-
20,21,Ethan Clark,PQR College,Computer Science,7.9,Yes,CodeWorks
21,22,Mia Roberts,XYZ University,Mechanical Engg,6.8,No,-
22,23,Noah Davis,ABC Institute,Electrical Engg,9.2,Yes,ElectroTech
23,24,Ava Miller,PQR College,Civil Engg,6.4,No,-
24,25,Lucas Allen,XYZ University,IT,8.7,Yes,SoftNet
25,26,Emma Walker,ABC Institute,Mechanical Engg,7.5,Yes,MechTech
26,27,Mason Perez,XYZ University,Electrical Engg,8.3,Yes,PowerGrid
27,28,Isabella Lee,PQR College,Computer Science,9.0,Yes,TechCorp
28,29,Jacob Brown,ABC Institute,IT,7.2,No,-
29,30,Charlotte Kim,XYZ University,Civil Engg,6.6,No,-
30,31,Olivia Green,PQR College,Computer Science,8.6,Yes,CodeWorks
31,32,Elijah Adams,ABC Institute,Mechanical Engg,7.7,Yes,MechTech
32,33,Amelia King,XYZ University,Electrical Engg,9.3,Yes,ElectroTech
33,34,Logan White,PQR College,Civil Engg,6.5,No,-
34,35,Harper Smith,ABC Institute,IT,8.1,Yes,SoftNet
35,36,James Taylor,XYZ University,Electrical Engg,7.8,Yes,PowerGrid
36,37,Ella Brown,PQR College,Computer Science,8.9,Yes,TechCorp
37,38,Henry Harris,ABC Institute,Mechanical Engg,6.9,No,-
38,39,Chloe Wilson,XYZ University,IT,9.1,Yes,SoftNet
39,40,Benjamin Ray,PQR College,Civil Engg,6.7,No,-
40,41,Liam Harris,XYZ University,Computer Science,8.5,Yes,TechCorp
41,42,Sophia Davis,ABC Institute,Civil Engg,6.8,No,-
42,43,Logan White,PQR College,Electrical Engg,9.3,Yes,ElectroTech
43,44,Ava Johnson,XYZ University,IT,7.1,No,-
44,45,Ethan Carter,ABC Institute,Mechanical Engg,8.4,Yes,MechTech
45,46,Mia Wilson,PQR College,Electrical Engg,9.0,Yes,PowerGrid
46,47,Harper Moore,XYZ University,Computer Science,7.5,Yes,CodeWorks
47,48,Mason Clark,ABC Institute,Civil Engg,6.6,No,-
48,49,Ella Brown,PQR College,IT,8.2,Yes,SoftNet
49,50,Henry Taylor,XYZ University,Electrical Engg,7.9,Yes,ElectroTech
50,51,Emily Johnson,ABC Institute,Mechanical Engg,8.7,Yes,MechTech
51,52,Amelia Green,PQR College,IT,7.3,No,-
52,53,Chloe Harris,XYZ University,Computer Science,8.8,Yes,TechCorp
53,54,Lucas White,ABC Institute,Electrical Engg,9.4,Yes,PowerGrid
54,55,Olivia Brown,PQR College,Mechanical Engg,7.7,Yes,MechTech
55,56,Noah Lee,XYZ University,Civil Engg,6.5,No,-
56,57,Charlotte Kim,ABC Institute,IT,8.6,Yes,SoftNet
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech
58,59,Emma Walker,XYZ University,Computer Science,7.8,Yes,CodeWorks
59,60,Benjamin Gray,ABC Institute,Mechanical Engg,6.9,No,-

In [13]:
df1.head(6)

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,NaN
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,NaN
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech

In [14]:
df1.tail()

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
55,56,Noah Lee,XYZ University,Civil Engg,6.5,No,NaN
56,57,Charlotte Kim,ABC Institute,IT,8.6,Yes,SoftNet
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech
58,59,Emma Walker,XYZ University,Computer Science,7.8,Yes,CodeWorks
59,60,Benjamin Gray,ABC Institute,Mechanical Engg,6.9,No,-

In [15]:
df1.columns

Index(['stud_id', 'stud_name', 'college_name', 'course', 'cgpa',
       'placed or not', 'company_name'],
      dtype='object')

In [16]:
df1.dtypes

stud_id            int64
stud_name         object
college_name      object
course            object
cgpa             float64
placed or not     object
company_name      object
dtype: object

In [17]:
df1.describe()

         stud_id       cgpa
count  60.000000  59.000000
mean   30.500000   7.938983
std    17.464249   0.967759
min     1.000000   6.300000
25%    15.750000   7.000000
50%    30.500000   7.900000
75%    45.250000   8.800000
max    60.000000   9.400000

In [18]:
df1.shape

(60, 7)

In [19]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stud_id        60 non-null     int64
 1   stud_name      60 non-null     object
 2   college_name   60 non-null     object
 3   course         60 non-null     object
 4   cgpa           59 non-null     float64
 5   placed or not  60 non-null     object
 6   company_name   54 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 3.4+ KB

In [20]:
df1.loc[9]

stud_id                      10
stud_name           Laura White
college_name     XYZ University
course               Civil Engg
cgpa                        6.3
placed or not                No
company_name                  -
Name: 9, dtype: object

In [21]:
df1.iloc[9]

stud_id                      10
stud_name           Laura White
college_name     XYZ University
course               Civil Engg
cgpa                        6.3
placed or not                No
company_name                  -
Name: 9, dtype: object

In [22]:
df1.isnull().sum()

stud_id          0
stud_name        0
college_name     0
course           0
cgpa             1
placed or not    0
company_name     6
dtype: int64

In [23]:
df1.fillna({'company_name':'NA'},inplace=True)

In [24]:
df1.isnull().sum()

stud_id          0
stud_name        0
college_name     0
course           0
cgpa             1
placed or not    0
company_name     0
dtype: int64

In [25]:
df1

,stud_id,stud_name,college_name,course,cgpa,placed or not,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,NA
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,NA
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech
6,7,Mark Blue,XYZ University,Electrical Engg,8.5,Yes,PowerGrid
7,8,Jenny Clark,ABC Institute,Computer Science,7.6,No,-
8,9,Kevin Gray,PQR College,IT,9.0,Yes,SoftNet
9,10,Laura White,XYZ University,Civil Engg,6.3,No,-
10,11,Rachel Adams,XYZ University,Computer Science,8.1,Yes,TechCorp
11,12,Peter Jones,ABC Institute,Mechanical Engg,6.9,No,-
12,13,Adam Carter,PQR College,IT,9.4,Yes,SoftNet
13,14,Megan Hall,XYZ University,Electrical Engg,7.8,Yes,ElectroTech
14,15,Olivia Black,ABC Institute,Civil Engg,6.5,No,-
15,16,David Green,PQR College,Computer Science,8.9,Yes,CodeWorks
16,17,Jessica Ray,XYZ University,Mechanical Engg,NaN,No,NA
17,18,Harry James,PQR College,IT,8.7,Yes,SoftNet
18,19,Sophia King,ABC Institute,Electrical Engg,9.1,Yes,PowerGrid
19,20,Liam Brown,XYZ University,Civil Engg,6.8,No,-
20,21,Ethan Clark,PQR College,Computer Science,7.9,Yes,CodeWorks
21,22,Mia Roberts,XYZ University,Mechanical Engg,6.8,No,-
22,23,Noah Davis,ABC Institute,Electrical Engg,9.2,Yes,ElectroTech
23,24,Ava Miller,PQR College,Civil Engg,6.4,No,-
24,25,Lucas Allen,XYZ University,IT,8.7,Yes,SoftNet
25,26,Emma Walker,ABC Institute,Mechanical Engg,7.5,Yes,MechTech
26,27,Mason Perez,XYZ University,Electrical Engg,8.3,Yes,PowerGrid
27,28,Isabella Lee,PQR College,Computer Science,9.0,Yes,TechCorp
28,29,Jacob Brown,ABC Institute,IT,7.2,No,-
29,30,Charlotte Kim,XYZ University,Civil Engg,6.6,No,-
30,31,Olivia Green,PQR College,Computer Science,8.6,Yes,CodeWorks
31,32,Elijah Adams,ABC Institute,Mechanical Engg,7.7,Yes,MechTech
32,33,Amelia King,XYZ University,Electrical Engg,9.3,Yes,ElectroTech
33,34,Logan White,PQR College,Civil Engg,6.5,No,-
34,35,Harper Smith,ABC Institute,IT,8.1,Yes,SoftNet
35,36,James Taylor,XYZ University,Electrical Engg,7.8,Yes,PowerGrid
36,37,Ella Brown,PQR College,Computer Science,8.9,Yes,TechCorp
37,38,Henry Harris,ABC Institute,Mechanical Engg,6.9,No,NA
38,39,Chloe Wilson,XYZ University,IT,9.1,Yes,SoftNet
39,40,Benjamin Ray,PQR College,Civil Engg,6.7,No,NA
40,41,Liam Harris,XYZ University,Computer Science,8.5,Yes,TechCorp
41,42,Sophia Davis,ABC Institute,Civil Engg,6.8,No,-
42,43,Logan White,PQR College,Electrical Engg,9.3,Yes,ElectroTech
43,44,Ava Johnson,XYZ University,IT,7.1,No,-
44,45,Ethan Carter,ABC Institute,Mechanical Engg,8.4,Yes,MechTech
45,46,Mia Wilson,PQR College,Electrical Engg,9.0,Yes,PowerGrid
46,47,Harper Moore,XYZ University,Computer Science,7.5,Yes,CodeWorks
47,48,Mason Clark,ABC Institute,Civil Engg,6.6,No,-
48,49,Ella Brown,PQR College,IT,8.2,Yes,SoftNet
49,50,Henry Taylor,XYZ University,Electrical Engg,7.9,Yes,ElectroTech
50,51,Emily Johnson,ABC Institute,Mechanical Engg,8.7,Yes,MechTech
51,52,Amelia Green,PQR College,IT,7.3,No,-
52,53,Chloe Harris,XYZ University,Computer Science,8.8,Yes,TechCorp
53,54,Lucas White,ABC Institute,Electrical Engg,9.4,Yes,PowerGrid
54,55,Olivia Brown,PQR College,Mechanical Engg,7.7,Yes,MechTech
55,56,Noah Lee,XYZ University,Civil Engg,6.5,No,NA
56,57,Charlotte Kim,ABC Institute,IT,8.6,Yes,SoftNet
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech
58,59,Emma Walker,XYZ University,Computer Science,7.8,Yes,CodeWorks
59,60,Benjamin Gray,ABC Institute,Mechanical Engg,6.9,No,-

In [26]:
df1.columns

Index(['stud_id', 'stud_name', 'college_name', 'course', 'cgpa',
       'placed or not', 'company_name'],
      dtype='object')

In [27]:
df1.rename(columns={'placed or not':'placed'}, inplace=True)

In [28]:
df1.columns

Index(['stud_id', 'stud_name', 'college_name', 'course', 'cgpa', 'placed',
       'company_name'],
      dtype='object')

In [29]:
df1['stud_name']

0        John Smith
1       Alice Brown
2         Bob White
3         Sarah Lee
4         Tom Black
5       Emily Green
6         Mark Blue
7       Jenny Clark
8        Kevin Gray
9       Laura White
10     Rachel Adams
11      Peter Jones
12      Adam Carter
13       Megan Hall
14     Olivia Black
15      David Green
16      Jessica Ray
17      Harry James
18      Sophia King
19       Liam Brown
20      Ethan Clark
21      Mia Roberts
22       Noah Davis
23       Ava Miller
24      Lucas Allen
25      Emma Walker
26      Mason Perez
27     Isabella Lee
28      Jacob Brown
29    Charlotte Kim
30     Olivia Green
31     Elijah Adams
32      Amelia King
33      Logan White
34     Harper Smith
35     James Taylor
36       Ella Brown
37     Henry Harris
38     Chloe Wilson
39     Benjamin Ray
40      Liam Harris
41     Sophia Davis
42      Logan White
43      Ava Johnson
44     Ethan Carter
45       Mia Wilson
46     Harper Moore
47      Mason Clark
48       Ella Brown
49     Henry Taylor
50    Emily Johnson
51     Amelia Green
52     Chloe Harris
53      Lucas White
54     Olivia Brown
55         Noah Lee
56    Charlotte Kim
57      James Adams
58      Emma Walker
59    Benjamin Gray
Name: stud_name, dtype: object

In [31]:
df1[df1['cgpa']>9.0]

,stud_id,stud_name,college_name,course,cgpa,placed,company_name
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
12,13,Adam Carter,PQR College,IT,9.4,Yes,SoftNet
18,19,Sophia King,ABC Institute,Electrical Engg,9.1,Yes,PowerGrid
22,23,Noah Davis,ABC Institute,Electrical Engg,9.2,Yes,ElectroTech
32,33,Amelia King,XYZ University,Electrical Engg,9.3,Yes,ElectroTech
38,39,Chloe Wilson,XYZ University,IT,9.1,Yes,SoftNet
42,43,Logan White,PQR College,Electrical Engg,9.3,Yes,ElectroTech
53,54,Lucas White,ABC Institute,Electrical Engg,9.4,Yes,PowerGrid
57,58,James Adams,PQR College,Electrical Engg,9.1,Yes,ElectroTech

In [32]:
df1['marks']=df1['stud_id']*5

In [33]:
df1.columns

Index(['stud_id', 'stud_name', 'college_name', 'course', 'cgpa', 'placed',
       'company_name', 'marks'],
      dtype='object')

In [34]:
df1.head(2)

,stud_id,stud_name,college_name,course,cgpa,placed,company_name,marks
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp,5
1,2,Alice Brown,ABC Institute,Mechanical Engg,7.1,No,NA,10

In [35]:
df1.drop('marks',axis=1,inplace=True)

In [36]:
df1.columns

Index(['stud_id', 'stud_name', 'college_name', 'course', 'cgpa', 'placed',
       'company_name'],
      dtype='object')

In [37]:
df1.dtypes

stud_id           int64
stud_name        object
college_name     object
course           object
cgpa            float64
placed           object
company_name     object
dtype: object

In [38]:
df1.index

RangeIndex(start=0, stop=60, step=1)

In [39]:
df1.drop(index=[1],inplace=True)

In [40]:
df1.head()

,stud_id,stud_name,college_name,course,cgpa,placed,company_name
0,1,John Smith,XYZ University,Computer Science,8.4,Yes,TechCorp
2,3,Bob White,PQR College,Electrical Engg,8.8,Yes,ElectroTech
3,4,Sarah Lee,XYZ University,Civil Engg,6.7,No,NA
4,5,Tom Black,ABC Institute,IT,9.2,Yes,CodeWorks
5,6,Emily Green,PQR College,Mechanical Engg,7.3,Yes,MechTech

In [41]:
avg_cgpa=df1.groupby('college_name')['cgpa'].mean()
avg_cgpa

college_name
ABC Institute     7.850000
PQR College       8.247368
XYZ University    7.776190
Name: cgpa, dtype: float64

In [42]:
df1['cgpa'].sum()

461.3

In [43]:
df1['cgpa'].mean()

7.953448275862069

In [ ]:
import matplotlib.pyplot as plt